#define MAINPREFIX z
#define PREFIX smm

#include "script_version.hpp"

#define VERSION         MAJOR.MINOR
#define VERSION_STR     MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR      MAJOR,MINOR,PATCHLVL,BUILD
#define VERSION_PLUGIN  MAJOR.MINOR.PATCHLVL.BUILD

#define REQUIRED_VERSION 3.00

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(SMM COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(SMM COMPONENT)
#endif
